name: Engineer Features Daily

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  engineer-features:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Feature Engineering
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        echo "$HOPSWORKS_API_KEY" > hopsworks_api_key.txt
        export HOPSWORKS_API_KEY=$(cat hopsworks_api_key.txt)
        python feature_scripts.py
